<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-7859aec032bf2e2"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-7859aec032bf34e"><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-7859aec032bf3ad"><div class="tcb-flex-col" data-css="tve-u-7859aec032bf413" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-7859aec032bf475"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-7859aec032bf4c5" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2427" alt="" width="198" height="179" title="set_27_icon" data-id="2427" src="{tve_leads_base_url}/images/set_27_icon.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col" data-css="tve-u-7859aec032bf512" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-7859aec032bf571"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-7859aec032bf5d3"><p data-css="tve-u-7859aec032bf637" data-default="Enter your text here...">Subscribe to the Newsletter!</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style=""><p data-css="tve-u-7859aec032bf691" data-default="Enter your text here...">Aenean sollicitudin, lorem quis bibendum auctor, nisi elit ipsum, nec sagittis sem nibh id elit.</p></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-7859aec032bf6dd"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--2 tcb-resized" data-css="tve-u-7859aec032bf738"><div class="tcb-flex-col" data-css="tve-u-7859aec032bf79b" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input tcb-icon-display tve_empty_dropzone" data-css="tve-u-7859aec032bf806">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-7859aec032bf8a6" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-7859aec032bf8fe">
<button type="submit" class="tve-froala" style="">SUBSCRIBE</button>
</div></div></div></div></div>
</div>
<input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"><input id="_submit_option" type="hidden" name="_submit_option" value="reload"><input id="_back_url" type="hidden" name="_back_url" value=""></form>
</div>
</div></div></div></div></div></div>