<div class="thrv-leads-form-box tve_no_drag tve_no_icons thrv_wrapper tve_editor_main_content thrv-leads-in-content tve_empty_dropzone" style="" data-css="tve-u-959aec157dadbe"><div class="thrv_wrapper thrv-columns" style="" data-css="tve-u-959aec157dae26"><div class="tcb-flex-row tcb-resized tcb--cols--2" data-css="tve-u-959aec157dae88"><div class="tcb-flex-col c-33" data-css="tve-u-959aec157daee6" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-959aec157daf4d"><div class="thrv_wrapper tve_image_caption" data-css="tve-u-959aec157dafab" style=""><span class="tve_image_frame" style="width: 100%;"><img class="tve_image wp-image-2450" alt="" width="186" height="283" title="set_60_product" data-id="2450" src="{tve_leads_base_url}/images/set_60_product.png" style="width: 100%;"></span></div></div></div><div class="tcb-flex-col c-66" data-css="tve-u-959aec157db00b" style=""><div class="tcb-col tve_empty_dropzone" style="" data-css="tve-u-959aec157db068"><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-959aec157db0c6"><p data-css="tve-u-959aec157db124" data-default="Enter your text here..."><span data-css="tve-u-959aec157db182" style="font-family: Cookie; font-weight: 400; font-size: 60px;">12 Free Tips</span> to Master Self-Made Business Success</p></div><div class="thrv_wrapper thrv_text_element tve_empty_dropzone" style="" data-css="tve-u-959aec157db1e0"><p data-css="tve-u-959aec157db25b" data-default="Enter your text here...">Sign up below to get started  with our FREE course:</p></div><div class="thrv_wrapper thrv_lead_generation" data-connection="api" style="" data-css="tve-u-959aec157db2c9"><input type="hidden" class="tve-lg-err-msg" value="{&quot;email&quot;:&quot;Email address invalid&quot;,&quot;phone&quot;:&quot;Phone number invalid&quot;,&quot;password&quot;:&quot;Password invalid&quot;,&quot;passwordmismatch&quot;:&quot;Password mismatch error&quot;,&quot;required&quot;:&quot;Required field missing&quot;}">
<div class="thrv_lead_generation_container tve_clearfix">
<form action="#" method="post" novalidate="novalidate">
<div class="tve_lead_generated_inputs_container tve_clearfix tve_empty_dropzone">
<div class="thrv_wrapper thrv-columns"><div class="tcb-flex-row tcb--cols--2 tcb-resized"><div class="tcb-flex-col" data-css="tve-u-959aec157db330" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_lg_input" data-css="tve-u-959aec157db399">
<input type="email" data-field="email" data-required="1" data-validation="email" name="email" placeholder="Email" data-placeholder="Email" class="" style="">
</div></div></div><div class="tcb-flex-col" data-css="tve-u-959aec157db3fd" style=""><div class="tcb-col tve_empty_dropzone"><div class="tve_lg_input_container tve_submit_container tve_lg_submit" data-css="tve-u-959aec157db469">
<button type="submit" class="tve-froala" style="">GET IT NOW</button>
</div></div></div></div></div>
</div>
<input type="hidden" name="__tcb_lg_fc" id="__tcb_lg_fc" value="YTowOnt9"><input id="_submit_option" type="hidden" name="_submit_option" value="reload"><input id="_back_url" type="hidden" name="_back_url" value=""></form>
</div>
</div></div></div></div></div></div>